---
name: Add pull request labels

on:
  workflow_call:

jobs:
  add-pr-label:
    name: Add PR Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Bullfrog Secure Runner
        uses: bullfrogsec/bullfrog@v0
        with:
          egress-policy: audit

      - name: Checkout reusable actions repo
        uses: actions/checkout@v3
        with:
          repository: vyos/.github
          path: reusable-actions
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ./reusable-actions/.github/labeler.yml
