name: "PR Triage"
on:
  workflow_call:

jobs:
  # https://github.com/marketplace/actions/auto-author-assign
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Bullfrog Secure Runner
        uses: bullfrogsec/bullfrog@v0
        with:
          egress-policy: audit

      - name: "Assign Author to PR"
        uses: toshimaru/auto-author-assign@v1.6.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
