name: "Check PRs conflict"
on:
  workflow_call:

jobs:
  prs-conflict-Check:
    name: 'Check PRs status: conflicts and resolution'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Bullfrog Secure Runner
        continue-on-error: true
        uses: bullfrogsec/bullfrog@v0.8.4
        with:
          egress-policy: audit

      - name: check if PRs are dirty
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "conflicts"
          removeOnDirtyLabel: "state: conflict resolved"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          retryAfter: 120
          retryMax: 10
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
