name: Check for unused imports using Pylint 
on:
  workflow_call:
jobs:
  check-unused-imports:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:

      - name: Checkout pull request merge ref
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          repository: ${{ github.event.pull_request.base.repo.full_name }}

      - name: Get changed files
        id: changed-files
        uses: actions/github-script@v4
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: files } = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            const changedFiles = files.map(file => file.filename).filter(file => file.startsWith('src/'));
            console.log("Changed files:", changedFiles);
            core.setOutput('result', changedFiles.join(','));

      - name: Print changed files
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.result }}"

      - name: Check unused imports (pylint)
        if: steps.changed-files.outputs.result != ''
        run: |
          set +e
          py_files=$(echo ${{ steps.changed-files.outputs.result }} | tr ',' ' ')
          output=$(pylint --disable=all --enable=W0611 $py_files)
          exit_code=$?
          set -e
          echo "$output"
          run_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          message=":white_check_mark: No issues found in *unused-imports* check."
          if [[ $exit_code -ne 0 ]]; then
            message=":x: Issues found in *unused-imports* check. "
          fi
          echo "WORKFLOW_MESSAGE=${message}. Please refer the [workflow run]($run_url)" >> $GITHUB_ENV
          exit $exit_code