---
  name: Check pull request message format
  
  on:
    workflow_call:

  env:
    GH_TOKEN: ${{ secrets.PAT }}
  
  jobs:
    check-pr-title:
      name: Check pull request title
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: read
      steps:
        - uses: actions/checkout@v3
          timeout-minutes: 2
    
        - name: Checkout reusable actions repo
          uses: actions/checkout@v3
          with:
            repository: vyos/.github
            path: reusable-actions
  
        - name: Install the requests library
          run: pip3 install requests
  
        - name: Check the PR title
          timeout-minutes: 2
          id: check_pr_title
          run: |
            source_pr_title=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json title -q .title)
            echo "source_pr_title=$source_pr_title"
            title_regex='^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'
            if [[ ! $source_pr_title =~ $title_regex ]]; then
              echo "PR title '$source_pr_title' does not match the required format!"
              echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
              echo "Valid title example: T99999: make IPsec secure"
              exit 1
            fi
            echo "PR title '$source_pr_title' is valid."

        - name: Check commit messages
          timeout-minutes: 2
          id: check_commit_messages
          run: |
            commit_regex='^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'
            commits=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json commits -q '.commits[].commit.message')
            for commit_message in $commits; do
              if [[ ! $commit_message =~ $commit_regex ]]; then
                echo "Commit message '$commit_message' does not match the required format!"
                echo "error_message=Commit message does not match the required format!" >> $GITHUB_ENV
                echo "Valid commit message example: T99999: make IPsec secure"
                exit 1
              fi
            done
            echo "All commit messages are valid."
            echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV

        - name: Add PR comment
          if: always()
          uses: mshick/add-pr-comment@v2
          with:
            message: |-
              ${{ env.error_message == 'No issues in PR Title / Commit Title' && '👍' || '❌' }}
              ${{ env.error_message }}
            message-id: "TITLE_COMMIT_VALIDATION"
            allow-repeats: false