---
  name: Check pull request message format
  
  on:
    workflow_call:

  env:
    GH_TOKEN: ${{ secrets.PAT }}
  
  jobs:
    check-pr-title:
      name: Check pull request title
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: read
      steps:
        - uses: actions/checkout@v3
          timeout-minutes: 2
    
        - name: Checkout reusable actions repo
          uses: actions/checkout@v3
          with:
            repository: vyos/.github
            path: reusable-actions
  
        - name: Check the PR title
          timeout-minutes: 2
          run: |
            source_pr_title=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json title -q .title)
            if echo "$source_pr_title" | grep -Pq '^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'; then
                echo "PR title '$source_pr_title' is valid."
                echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
            else
                echo "PR title '$source_pr_title' does not match the required format!"
                echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
                echo "Valid title example: T99999: make IPsec secure"
                exit 1
            fi
        
        - name: Check commit messages
          timeout-minutes: 2
          run: |
            # Fetch commit messages
            commits=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json commits -q '.commits[].messageHeadline')
            # Iterate over each commit message
            echo "$commits" | while IFS= read -r commit_message; do
              if echo "$commit_message" | grep -Pq '^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'; then
                  echo "Commit message '$commit_message' is valid."
              else
                  echo "Commit message '$commit_message' does not match the required format!"
                  echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
                  echo "Valid commit message example: T99999: make IPsec secure"
                  exit 1
              fi
            done
            echo "All commit messages are valid."
            echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV

        - name: Add PR comment
          if: always()
          uses: mshick/add-pr-comment@v2
          with:
            message: |-
              ${{ env.error_message == 'No issues in PR Title / Commit Title' && '👍' || '❌' }}
              ${{ env.error_message }}
            message-id: "TITLE_COMMIT_VALIDATION"
            allow-repeats: false