---
name: Build Pull Request Package

on:
  workflow_call:

jobs:
  j2lint:
    name: Validate j2 files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      
      - name: Bullfrog Secure Runner
        uses: bullfrogsec/bullfrog@v0
        with:
          egress-policy: audit

      - uses: actions/checkout@v2
        timeout-minutes: 2
      - name: Setup J2Lint
        timeout-minutes: 2
        run: |
          sudo pip install git+https://github.com/aristanetworks/j2lint.git@341b5d5db86e095b622f09770cb6367a1583620e
      - name: Run J2lint
        timeout-minutes: 2
        run: |
          j2lint $GITHUB_WORKSPACE/data
