name: Repo-sync by commit

on:
  workflow_call:
    inputs:
      source_repo:
        description: 'source_repo'
        required: true
        type: string
      source_commit_sha:
        description: 'source_commit_sha'
        required: true
        type: string
      destination_branch:
        description: 'destination_branch'
        required: true
        default: 'current'
        type: string
    secrets:
      PAT:
        required: true

run-name: Repo commit ${{ github.event.inputs.source_commit_sha }} sync for ${{ github.event.inputs.destination_branch }} branch

env:
  SOURCE_REPO: ${{ github.event.inputs.source_repo }}
  SOURCE_COMMIT_SHA: ${{ github.event.inputs.source_commit_sha }}
  DESTINATION_BRANCH: ${{ github.event.inputs.destination_branch }}
  GITHUB_TOKEN: ${{ secrets.PAT }}

concurrency:
  group: repo-sync-by-commit-${{ github.event.inputs.destination_branch }}
  cancel-in-progress: false
jobs:
  repo-sync:
    if: ${{ github.repository_owner != 'vyos' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Repo commit sync
      shell: bash
      run: |
        set -e
        SOURCE_REPO_URL="https://github.com/${SOURCE_REPO}.git"
        git config --unset-all http."https://github.com/".extraheader || :
        git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        git remote add tmp_source "$SOURCE_REPO_URL"
        git fetch tmp_source --quiet
        git push origin "${SOURCE_COMMIT_SHA}:refs/heads/${DESTINATION_BRANCH}" --force
        git remote rm tmp_source
