name: Workflow to trigger a package build

on:
  workflow_call:
    inputs:
      branch:
        description: 'PR target branch'
        required: true
        type: string
        default: circinus
      package_name:
        description: 'PR package name'
        required: true
        type: string
      REF:
        required: false
        type: string
        default: main
    secrets:
      REMOTE_OWNER:
        description: 'Remote repo owner'
        required: true
      REMOTE_REUSE_REPO:
        description: 'Remote reusable repo name'
        required: true
      GPG_KEY_ID:
        description: 'DEB repo GPG key ID'
        required: true
      PAT:
        description: 'Personal Access Token'
        required: true

jobs:
  trigger_package_build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Bullfrog Secure Runner
        uses: bullfrogsec/bullfrog@v0
        with:
          egress-policy: audit

      - name: Trigger rebuild for ${{ inputs.package_name }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REUSE_REPO }}/actions/workflows/build-package.yml/dispatches \
            -d '{"ref": "${{ inputs.REF }}", "inputs":{"package_name":"${{ inputs.package_name }}", "gpg_key_id": "${{ secrets.GPG_KEY_ID }}", "package_branch": "${{ inputs.branch }}"}}'
