name: Workflow to trigger a package build

on:
  workflow_call:
        inputs:
            branch:
                required: true
                type: string
                default: current
            package_name:
                required: true
                type: string
            REF:
                required: true
                type: string
                default: main
        secrets:
            REMOTE_OWNER:
                required: true
            REMOTE_REUSE_REPO:
                required: true
            GPG_KEY_ID:
                required: true
            PAT:
                required: true

jobs:
  trigger_package_build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger rebuild for ${{ inputs.package_name }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REUSE_REPO }}/actions/workflows/build-package.yml/dispatches \
            -d '{"ref": "${{ inputs.REF }}", "inputs":{"package_name":"${{ inputs.package_name }}", "gpg_key_id": "${{ secrets.GPG_KEY_ID }}", "package_branch": "${{ inputs.branch }}"}}'
