---
name: Trigger repo sync sagitta

on:
  workflow_call:
    secrets:
      REMOTE_OWNER:
        description: 'Remote repo owner'
        required: true
      REMOTE_REPO:
        description: 'Remote repo name'
        required: true
      PAT:
        description: 'Personal Access Token'
        required: true

jobs:
  trigger-repo-sync:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:

      - name: Trigger sync workflow
        shell: bash
        run: |
          echo "Triggering sync workflow for ${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REPO }}"
          echo "Triggering sync workflow with PAT ${{ secrets.PAT }}"
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REPO }}/actions/workflows/repo-sync-sagitta.yml/dispatches \
            -d '{"ref":"git-actions"}'
